### PR TITLE
[Fix: issue 542] changes to str when column data is a list or tuple in pc.data_table

### PR DESCRIPTION
**Pull request by d29107d**
### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully run tests with your changes locally?

### Description
    
[Fix issue 542](https://github.com/pynecone-io/pynecone/issues/542)
changes to str when column data is a list or tuple in pc.data_table

### CODE REVIEW

**Comment by Alek99** [comment]
Ok nice going to test this locally tonight

**Review by Alek99 — CHANGES_REQUESTED** [review]
Sorry for the delay response just checked out your pr and the results of the code from the issue is still showing as all together `123` and `456`. It should look like `['1', '2', '3']`
and `['4', '5', '6']` right?

**Comment by d29107d** [comment]
@Alek99 Yes
The codes like below:
```
# type: ignore
"""Welcome to Pynecone! This file outlines the steps to create a basic app."""
import pynecone as pc
import pandas as pd


class State(pc.State):
    data1 = pd.DataFrame(data=[{"parentBuildID": "P1", "childBuildID": 1},
                               {"parentBuildID": "P2", "childBuildID": (1, 2, 3)},
                               {"parentBuildID": "P3", "childBuildID": ['4', '5', '6']}])


def index():
    return pc.data_table(
        data=State().data1,
        pagination=True,
        search=True,
    )


app = pc.App(state=State)
app.add_page(index)
app.compile()

```

image

**Comment by Alek99** [comment]
Ok let me try that code

**Comment by Alek99** [comment]
```
# type: ignore
"""Welcome to Pynecone! This file outlines the steps to create a basic app."""
import pynecone as pc
import pandas as pd


class State(pc.State):
    data1 = pd.DataFrame(data=[{"parentBuildID": "P1", "childBuildID": 1},
                               {"parentBuildID": "P2", "childBuildID": (1, 2, 3)},
                               {"parentBuildID": "P3", "childBuildID": ['4', '5', '6']}])


def index():
    return pc.data_table(
        data=State.data1,
        pagination=True,
        search=True,
    )


app = pc.App(state=State)
app.add_page(index)
app.compile()
```

It seems to be creating a new state instance it will need to work with the above code where `data=State.data1` not `data=State().data1`

**Comment by d29107d** [comment]
@picklelo 
How to iterate a BaseVar? I get stuck here. :anguished: 
https://github.com/pynecone-io/pynecone/blob/46cdda41250d4c11b9a84bf75ab6cf4b003cd933/pynecone/components/datadisplay/datatable.py#L88

**Review by picklelo — APPROVED** [review]
Tested it out and seems to work well - nice job!

**Pull request merged**
