### PR TITLE
Add bun install to fix pc bun package installation Error during run command in Container Image

### PR DESCRIPTION
**Pull request by r0b2g1t**
### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### New Feature Submission:

- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

The PR fixes the pc run error in the container build of Pynecone which causes by the download issue in the production environment of Pynecone. The bun package download is triggered via bun command. That fixed the issue #897.

### CODE REVIEW

**Comment by ElijahAhianyo** [comment]
this PR seems to be in conflict with #903 ?

**Comment by r0b2g1t** [comment]
> this PR seems to be in conflict with #903 ?

the PR #903 would be rendered superfluous by this.

**Comment by Alek99** [comment]
Nice fix will test this today

**Comment by Alek99** [comment]
pc init installs bun can we get rid of all the custom bun install logic?

This is the command run:
# Command to install bun.
INSTALL_BUN = "curl -fsSL https://bun.sh/install | bash -s -- bun-v0.5.9"

**Comment by r0b2g1t** [comment]
> pc init installs bun can we get rid of all the custom bun install logic?
> 
> 
> 
> This is the command run:
> 
> 
> 
> INSTALL_BUN = "curl -fsSL https://bun.sh/install | bash -s -- bun-v0.5.9"

Tha ks for your question. You mean the command line:

bash -c "/app/.bun/bin/bun install --cwd .web/"

This line installs the package (next,...) by bun. It will not install bun it self. Bun will installed by pc init.

It is the fix of the not working package installation in the container image of the issue #897.

**Comment by milochen0418** [comment]
@Alek99 @r0b2g1t 
When I test nba example from `pynecone-io/pynecone-examples`, I find out some projects could not run well in the first time.
When pynecone initialize nba example,it may miss to do `~/.bun/bin/bun install --cwd .web/` in some case. 

I'm sure nba example will always reproduce this problem.
https://github.com/pynecone-io/pynecone-examples/issues/63

I'm not sure if this information can help or not.

**Comment by r0b2g1t** [comment]
> @Alek99 @r0b2g1t When I test nba example from `pynecone-io/pynecone-examples`, I find out some projects could not run well in the first time. When pynecone initialize nba example,it may miss to do `~/.bun/bin/bun install --cwd .web/` in some case.
> 
> I'm sure nba example will always reproduce this problem.
> 
> * [pc init issue on nba example: pc  init cannot afford to run well in the first time pynecone-examples#63](https://github.com/pynecone-io/pynecone-examples/issues/63)
> 
> I'm not sure if this information can help or not.

Thanks for your feedback. Do you updated the ```pcconfig.py``` described in the container example readme? Because the path to the bun file is changed to ```bun_path="/app/.bun/bin/bun"``` which is located in the app directory for a more cleaner image build.

**Comment by r0b2g1t** [comment]
Fixed by #938

**Pull request closed without merging**
