### PR TITLE
Patch for #512 --no-frontend now updates database appropriately

### LINKED ISSUE #512: Running pc run --no-front-end fails to update DB when adding a model
**Describe the bug**
I host my app's frontend and backends on separate servers. Therefore only pynecone.db matters on the backend server. However, when adding some features to my app I noticed that my frontend which runs pc run --no-backend added a new table (model) but my backend which runs pc run --no-frontend did not which obviously caused my app to throw an error when the backend tried to interact with that table. 

**To Reproduce**
Add class ModelName(pc.Model): ... to a project and run separate frontend and backends. 
 - Code/Link to Repo:
https://github.com/codingjq/rapple-pyne
**Expected behavior**
I expect the --no-backend to not update its db while the --no-front-end does.

** Specifics (please complete the following information):**
 - Python Version: 3.10.7
 - Pynecone Version: 0.1.14
 - OS: ubuntu server 22.04

### PR DESCRIPTION
**Pull request by jqwez**
### All Submissions:

- [Y] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [Y] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [Y] Bug fix (non-breaking change which fixes an issue)

### New Feature Submission:

- [Y] Does your submission pass the tests? 

### Changes To Core Features:

- [Y] Have you added an explanation of what your changes do and why you'd like us to include them?
- [Y] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

I added the behavior from app.compile which updates the database to the circumstance that needs to update the database but not the rest of app.compile. 

closes #512

### CODE REVIEW

**Comment by jqwez** [comment]
closes #512

**Review by picklelo — COMMENTED** [review]
This looks good! Should we remove the `Model.create_all()` line in `app.py` so that we don't create the models twice?

**Comment by jqwez** [comment]
> This looks good! Should we remove the `Model.create_all()` line in `app.py` so that we don't create the models twice?

That makes sense. I don't see a case where someone running --no-backend needs the db models to update.

**Review by picklelo — APPROVED** [review]
Sweet!

**Pull request merged**
