### PR TITLE
Add anchor tag for hash link

### PR DESCRIPTION
**Pull request by PeterYusuke**
PR for issue #416.

### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### New Feature Submission:

- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

### **After** these steps, you're ready to open a pull request.

Added anchor tag that created with key property at any component.
This allows us to jump to to a specific place using hash in URL like "destination/url/#target".

Usage:

```py
    pc.box(
        pc.text("This is target"),
        key="target",
    )
```

Above code creates this.
Anchor tag is placed at the first child tag.
```js
    <Box key="target">
        <a name="target" id="target"></a>
        <Text>{`This is target`}</Text>
    </Box>
```

### CODE REVIEW

**Comment by Lendemor** [comment]
Is it not possible to add the `id` directly to the <Box> tag in this case?

**Comment by PeterYusuke** [comment]
> Is it not possible to add the `id` directly to the `<Box>` tag in this case?

I think it's possible. Should I change this?

**Comment by Alek99** [comment]
> > Is it not possible to add the `id` directly to the `<Box>` tag in this case?
> 
> I think it's possible. Should I change this?

Yeah it would simplify the compiled code a bit, can you try this and see if it works. Thanks for the contribution

**Review by picklelo — COMMENTED** [review]
Good calling adding this `id` field . I'm a bit confused though - looks like the Anchor class got reverted? Don't we need that?

**Review by picklelo — APPROVED** [review]
Nvm, tried this locally and it works great - awesome work!

**Comment by Lendemor** [comment]
> Good calling adding this `id` field . I'm a bit confused though - looks like the Anchor class got reverted? Don't we need that?

I think it was just there as a support for the `id` prop, but the Anchor itself didn't have a purpose.
Adding the `id` directly on the component work the same.

**Comment by mister-rao** [comment]
was looking for anchor hash navigation. Adding id to components work, but is there any way to make the scrolling smooth ?

**Pull request merged**
