### PR TITLE
[Enhancement Issue #1086] Add pc init --psog to create .gitignore fil…

### PR DESCRIPTION
**Pull request by milochen0418**
…e support putting pure source code on git

### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### New Feature Submission:

- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

This PR is related to the issue.
- https://github.com/pynecone-io/pynecone/issues/1086
When you want to create a new project with .gitignore, support pure source code on the git.
Maybe you don't want to push Python compiled code on the git. Then you can use it.

$ pc init --psog
$ cat .gitignore
```
pynecone.db
*.py[cod]
__pycache__/
.web
```

### CODE REVIEW

**Review by chrisrosner — COMMENTED** [review]
Is there any reason to make this optional? Seems like it'd be a sensible default.

**Comment by TaiJuWu** [comment]
Maybe you can add these files to gitignore   without option because they shouldn’t be put on GitHub.

**Comment by milochen0418** [comment]
> Is there any reason to make this optional? Seems like it'd be a sensible default.


@chrisrosner 

Because the Old PR cannot allow itbas default. And I don't know why. So the tradeoff way is to add --psog
https://github.com/pynecone-io/pynecone/pull/718

Do you have any suggestion or reason about why it should push __pycache__ on git in default ?

**Comment by milochen0418** [comment]
@chrisrosner, could you accept this PR?
Just let Pynecone's core team decide which approved PR can merge to Pynecone project.
You don't know why Pynecone's core team doesn't support `__pycache__` .gitignore. 
I don't know, either.   They may have their reason, but at least they agree on this issue
- https://github.com/pynecone-io/pynecone/issues/1086

I have already posted this issue the core team has already accepted this enhancement. 
If you don't accept this PR, the best way is to discuss this issue. Not block PR here.

Could you give me a favor... 
I am just an application developer who has the requirement to have a pure source code on git.

If everyone wants to reject this request according to their preferences and refuses to discuss or give a clear reason, the developer will always suffer. 

Can anyone discuss this special issue? 
Could you talk about what you think and hear what other people say?
@TaiJuWu @Alek99 @chrisrosner  @picklelo  @Lendemor @ElijahAhianyo 

As an application developer,  I don't care which one is better, but I need at least one way can let me create a `.gitignore` file that supports pure source code on git. 

I can understand everyone has a strong position they want to hold and may doesn't care about other people.
We need to find the tradeoff together. 

To have `pc init --psog`  method to create .gitignore is at least better than no .gitignore supporting pure source code on git forever. 

Could you give me a favor, please.

**Comment by milochen0418** [comment]
After communication, we have the summmary.  
--
In the discord #opensource channel, there is a discuss about this PR. 
Because there are at least 3 .gitignore files in the pynecone app project 
- app's root
- app (python part named as app_name you set in pc init)
- web (web part   named as .web)
After discussion and understanding, I explain what happened in the discord channel. 

.gitignore will influent each other .gitignore. The core team needs to think about how to manage them to get the most flexibility first. And then we can start to think what to do next.  
In the future, the solution maybe is the copying some .gitignore file to the app's root, or support some other thing to solve.  Or some other way else.

**Comment by picklelo** [comment]
Merged in #718 instead to have it by default

**Pull request closed without merging**
