### PR TITLE
Add windows support

### PR DESCRIPTION
**Pull request by picklelo**
One silly little `.strip()` made all the difference...

### CODE REVIEW

**Review by Alek99 — APPROVED** [review]
🪟

**Comment by forhonourlx** [comment]
Hi, how's the progress about supporting Windows?

**Comment by picklelo** [comment]
@forhonourlx We just released a new version (v0.1.13) that should now have Windows support. Could you try it and see if the issues are resolved?

**Comment by forhonourlx** [comment]
Great work! Well running in Windows! Thanks

**Pull request merged**
