### PR TITLE
switch to `httpx` (#74)

### PR DESCRIPTION
**Pull request by FHU-yezi**

### CODE REVIEW

**Comment by picklelo** [comment]
Code looks good, I'll look into the Github Actions failure... we can merge once it's passing

**Review by picklelo — APPROVED** [review]

**Review by Alek99 — APPROVED** [review]

**Comment by FHU-yezi** [comment]
I know why the CI is fail. Poetry just released a new version of lock file, and I use the latest version. When I run `poetry lock` to sync the lock file with the TOML file, it automaticlly update the lock file to the latest version.

Update the `poetry` dependence to latest version should solve this problem.

**Comment by FHU-yezi** [comment]
I got some error when I try to push the commit to my repo:

```
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/FHU-yezi/pynecone.git
 ! [remote rejected] httpx -> httpx (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/build.yml` without `workflow` scope)
```

Don't know how to deal with it, my change:

```yaml
# .github/workflows/build.yml, line 28
    - name: cache poetry install
      uses: actions/cache@v2
      with:
        path: ~/.local
        key: python-${{ matrix.python-version }}-poetry-1.2.2-0

    - uses: snok/install-poetry@v1
      with:
        version: 1.2.2
        virtualenvs-create: true
        virtualenvs-in-project: true
```

**Comment by picklelo** [comment]
I think you may not be able to update the CI jobs - I'll push a PR updating it the poetry version, then we can merge this.

**Comment by Alek99** [comment]
> I know why the CI is failed. Poetry just released a new version of lock file, and I use the latest version. When I run `poetry lock` to sync the lock file with the TOML file, it automaticlly update the lock file to the latest version.

Thanks good catch

**Comment by picklelo** [comment]
@FHU-yezi I just pushed a PR updating the poetry version, could you rebase this on top and push? Hopefully the build passes this time.

Btw, thanks for all your contributions and involvement with the project so far!

**Comment by FHU-yezi** [comment]
Just rebased my branch with the newest commits, and now the CI is running... But it failed again.

**Comment by FHU-yezi** [comment]
Read `httpx` documentation and tried by myself, this way of file upload will still work. Maybe developers don't think someone will upload files in request body directly, so I add some type ignores.

By the way, I removed some `f` which is unnesserary now.

**Review by picklelo — APPROVED** [review]
Awesome

**Pull request merged**
