### PR TITLE
feature: foreach support dict iterator

### LINKED ISSUE #912: pc.foreach iteration over other data types
Right now it can iterate over list but it should be able to iterate over dictionaries, sets, etc

### PR DESCRIPTION
**Pull request by TaiJuWu**
### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

### New Feature Submission:

- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [ x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ x] Have you written new tests for your core changes, as applicable?
- [ v] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.
         feature: foreach support dict iterator

    b. Describe your changes.
    In forEach class, It will convert syntax to Object.entries if the input type is dictionary.

```python3=
# example code

class ForeachState(pc.State):
    color = {  1 :  "red",
        2:"green",
        3:"blue",
        4:"yellow",
        5:"orange",
        6:"purple"}


def colored_box(items):
    return pc.box(pc.text(items[0]), bg=items[1])


def index():
    return pc.responsive_grid(
        pc.foreach(ForeachState.color, colored_box),
        columns=[2, 4, 6]
    )

app = pc.App(state=ForeachState)
app.add_page(index)
app.compile()
```
    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

fixes #912

### CODE REVIEW

**Review by ElijahAhianyo — APPROVED** [review]
nice work! lgtm

**Comment by Alek99** [comment]
Seems like its not passing integration test, I'll test it on pcweb on my local and try and reproduce

**Comment by Alek99** [comment]
Yeah was able to recreate looking into it more

**Comment by TaiJuWu** [comment]
@Alek99 Thank for your recreate,
I will try to fix this error

Is there any method to run integration test before I send PR?
I already try to modify integration_website.yml as below

```
name: integration-test

on:
  push:
    - main
```

**Comment by Alek99** [comment]
Not that I know of but, but what you can do to test is run https://github.com/pynecone-io/pcweb locally that's what the integration test is running. Try getting pcweb to work locally with your code and it should pass

**Comment by TaiJuWu** [comment]
Sorry, I failed to run pcweb.
But I discover some problem about pcweb.
In pcweb/components/navbar.py:39, it may be return list as the argument
```
def search_results(self) -> list[dict[str, dict[str, str]]]:
        if client is None or self.search_input == "":
            return []
```
And format_search_results as render function but its input look like a dictionary.
```
def format_search_results(result):
    return pc.vstack(
        pc.link(
            pc.text(
                result["document"]["heading"],
                font_weight=600,
                color=styles.DOC_HEADER_COLOR,
            )
```
I don't know what happened in this case.

**Comment by TaiJuWu** [comment]
The version can pass integration test.
And I find some problem about 
```type_ = self.iterable.type_.__args__[0]```
It should be return the type of elements in a list.
but in the example code from document
```
class ForeachState(pc.State):
    color = [
        "red",
        "green",
        "blue",
        "yellow",
        "orange",
        "purple",
    ]
def colored_box(color):
    return pc.box(pc.text(color), bg=color)


def index():
    print("ForeachState.color", ForeachState.color, type(ForeachState.color))
    
    return pc.responsive_grid(
        pc.foreach(ForeachState.color, colored_box),
        columns=[2, 4, 6]
    )
```
it will cause exception because type is <class list>

https://github.com/pynecone-io/pcweb/blob/a99d8cae613349cf11d0109aa441260e1cf15c0f/pcweb/components/navbar.py#L148-L151
The type is <Class types._GenericAlias>

**Pull request closed without merging**
