### PR TITLE
Update Dockerfile example

### PR DESCRIPTION
**Pull request by picklelo**

### CODE REVIEW

**Comment by r0b2g1t** [comment]
Hey I would not recommend this Dockerfile approach. It is less secure (running Pynecone as root) and the image size will be blown up by a lot of unnecessary software.

**Comment by r0b2g1t** [comment]
The Dockerfile is missing basic functions like the default entrypoint of the image. which is called when the image is started without command, as present in the current example. Likewise, Pynecone will launch the project in dev mode.  Likewise, Pynecone will launch the project in dev mode. In addition, an Ubuntu base image is not necessary, Python-slim is sufficient and is by far smaller than the result of the build. I would not recommend doing an image build based on this Dockerfile, as it gives the impression that it can be used productively that way.

**Review by r0b2g1t — CHANGES_REQUESTED** [review]
See comments before.

**Comment by Alek99** [comment]
I see nice fix will test this today.

**Pull request closed without merging**
