### PR TITLE
reinforce check for bun install process in "pc init"

### LINKED ISSUE #901: pc run failed - because bun's upgrading is not work from installation.
**Describe the bug**
In constants.py, we have 
```python
BUN_PATH = "$HOME/.bun/bin/bun"
INSTALL_BUN = "curl -fsSL https://bun.sh/install | bash -s -- bun-v0.5.9"
```

In pynecone/utils/prerequisites.py, we have 
```python
def install_bun():
    """Install bun onto the user's system.
    Raises:
        FileNotFoundError: If the required packages are not installed.
    """
    # Bun is not supported on Windows.
    if platform.system() == "Windows":
        console.log("Skipping bun installation on Windows.")
        return

    # Only install if bun is not already installed.
    if not os.path.exists(get_package_manager()):
        console.log("Installing bun...")

        # Check if curl is installed
        curl_path = path_ops.which("curl")
        if curl_path is None:
            raise FileNotFoundError("Pynecone requires curl to be installed.")

        # Check if unzip is installed
        unzip_path = path_ops.which("unzip")
        if unzip_path is None:
            raise FileNotFoundError("Pynecone requires unzip to be installed.")

        os.system(constants.INSTALL_BUN)
```
When the user calls `pc init`, the INSTALL_BUN will be invoked.
This installation will not automatically replace the old version, and the good thing is to avoid downloading again. 
The pynecone application developer doesn't need to know what bun version they use. 

If we change the bun version for fitting new pynecone, they will upgrade their pynecone package and then
find out `pc run` will get failed.

After my testing, the INSTALL_BUN can work well on my mac, we can replace any bun version by the command
https://github.com/pynecone-io/pynecone/pull/494

But the only issue of the logic is this logic condition
```python
    if not os.path.exists(get_package_manager()):
```
it check this path to decide updating bun or not. 

If you ever install pynecone install from 2023 Feb 10 
Then you can check `~/.bun/bin/bun --version` to see what bun version you have
And you can find out the bun version is old.

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: python 3.11
 - Pynecone Version: upgrading from old pynecone install from 2023 Feb 10  to 2023 Apr 24  version into 0.1.27
 - OS: Mac OS X 
 - Browser (Optional): Chrome
 
**Additional context**

### PR DESCRIPTION
**Pull request by Lendemor**
### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Changes To Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully ran tests with your changes locally?

## Changes

Refactor the installation process of bun, 
clean up the code 
and add a reinforced check for the version of bun (using `packaging.version`)

Closes #901

### CODE REVIEW

**Review by ElijahAhianyo — APPROVED** [review]

**Review by picklelo — APPROVED** [review]
awesome

**Comment by milochen0418** [comment]
wow~ nice :DD

**Comment by milochen0418** [comment]
@Lendemor  @ElijahAhianyo @picklelo  
Hi, 
It looks like the bun version checking doesn't  works
The following is my testing result for the new release 0.1.29 

Screenshot 2023-05-09 at 10 51 18 AM


Screenshot 2023-05-09 at 10 50 12 AM


Screenshot 2023-05-09 at 10 47 42 AM

**Comment by ElijahAhianyo** [comment]
Will look into this

**Pull request merged**
