### PR TITLE
[discussion 477] Compile file with using jinja.

### PR DESCRIPTION
**Pull request by PeterYusuke**
### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### New Feature Submission:

- [ ] Does your submission pass the tests? 
- [ ] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Description
This pr is about compiling files.
I use jinja for templating, so that we can read them more easily and maintainable.

Related #477.

### CODE REVIEW

**Comment by PeterYusuke** [comment]
I made this for discussing about testing jinja file.
Currently we have fotmating test, but changed to jinja some test cases will not need any more cause we can format them inside of template file.
I want some help.

**Comment by FHU-yezi** [comment]
Maybe you need to run `poetry install jinja2` to add this package to `pyproject.toml` and let the test pass.

**Comment by PeterYusuke** [comment]
> Maybe you need to run `poetry install jinja2` to add this package to `pyproject.toml` and let the test pass.

Right. Thank you for noticing me.

**Review by danik292 — DISMISSED** [review]

**Comment by PeterYusuke** [comment]
I'm so sorry.
My working branch was recognized as pull request branch.
I really messed up.
I Close this now.

**Pull request closed without merging**
