### PR TITLE
Fix auto primary key

### LINKED ISSUE #812: Fix id auto primary key
We currently always assume an primary key named `id` which can cause problems - let's fix this.

### PR DESCRIPTION
**Pull request by kasun**
### All Submissions:

Include automatically included primary key called `id` in child models only if no other primary key is defined.
Test model unit tests.

closes #812 

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### New Feature Submission:

- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by masenf** [comment]
My concern with this as written would be that it might trip up static analyzers.

**Comment by kasun** [comment]
> My concern with this as written would be that it might trip up static analyzers.

Because id is defined in Base but can be missing in child models? That is why added `optional` to id.

**Comment by masenf** [comment]
Screenshot 2023-04-20 at 9 02 16 PM

In the IDE, it thinks the model still has the `id` attribute...

not sure if that's really a problem, haven't tried to run it through mypy

**Comment by Alek99** [comment]
> Screenshot 2023-04-20 at 9 05 29 PM
> 
> In the IDE, it thinks the model still has the `id` attribute...
> 
> not sure if that's really a problem, haven't tried to run it through mypy. I guess if it's marked optional, then no one should really complain,

I see let me see if I get the same on my side

**Comment by Alek99** [comment]
Not getting the same for me, seems to be alright
Screen Shot 2023-04-24 at 6 30 35 PM

**Comment by Alek99** [comment]
> Screenshot 2023-04-20 at 9 05 29 PM
> 
> In the IDE, it thinks the model still has the `id` attribute...
> 
> not sure if that's really a problem, haven't tried to run it through mypy. I guess if it's marked optional, then no one should really complain,

@masenf Are you using vscode?

**Comment by Alek99** [comment]
I think it is fine for now can fix this in a follow up.

**Review by Alek99 — APPROVED** [review]
Nice!

**Pull request merged**
