### PR TITLE
feature: support Hightlight component

### LINKED ISSUE #1048: Highlight Component
Create a highlight component for Pynecone. This should be a fairly straightforward component as it follow a lot of the chakra components we use.

Great first issue for new contributors!

https://chakra-ui.com/docs/components/highlight

### PR DESCRIPTION
**Pull request by TaiJuWu**
### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

### New Feature Submission:

- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.
support Highlight component.
    b. Describe your changes.
support Highlight component and you have to notice styles and style is different prop.  Highlight uses styles.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
close #1048

### CODE REVIEW

**Comment by Alek99** [comment]
This code doesn't seem to be working for me can you provide an example?

**Comment by TaiJuWu** [comment]
```python
import pynecone as pc

class State(pc.State):
    """The app state."""

    text: str = "With the Highlight component, you can spotlight, emphasize and accentuate words."
    query=['spotlight', 'emphasize', 'Accentuate']
    styles={ 'px': '2', 'py': '1', 'rounded': 'full', 'bg': 'teal.100' }
    
    
def index():
    """The main view."""
    return pc.heading(
        pc.highlight(State.text, query=State.query, styles=State.styles)
    )
    
app = pc.App(state=State)
app.add_page(index)
app.compile()
```

**Comment by TaiJuWu** [comment]
> This code doesn't seem to be working for me can you provide an example?
Is this example working?
```python
import pynecone as pc

class State(pc.State):
    """The app state."""

    text: str = "With the Highlight component, you can spotlight, emphasize and accentuate words."
    query=['spotlight', 'emphasize', 'Accentuate']
    styles={ 'px': '2', 'py': '1', 'rounded': 'full', 'bg': 'teal.100' }
    
    
def index():
    """The main view."""
    return pc.heading(
        pc.highlight(State.text, query=State.query, styles=State.styles)
    )
    
app = pc.App(state=State)
app.add_page(index)
app.compile()
```

**Comment by Lendemor** [comment]
I think the `Highlight` component should provide a default `styles` in case the user didn't provide it.

**Comment by TaiJuWu** [comment]
> I think the `Highlight` component should provide a default `styles` in case the user didn't provide it.

Yes, you are right.

**Comment by TaiJuWu** [comment]
> For this component should we take the stye props and pass them into the style dict similar to how it's done in code block. This would allow code like
> 
> ```python
> class State(pc.State):
>     """The app state."""
> 
>     text: str = "With the Highlight component, you can spotlight, emphasize and accentuate words."
>     query=['spotlight', 'emphasize', 'Accentuate']
>     styles={ 'px': '2', 'py': '1', 'rounded': 'full', 'bg': 'teal.100' }
>     
>     def add_query(self, query: str):
>         """Add a query to the list of queries."""
>         self.query.append(query)
>     
> def index():
>     """The main view."""
>     
>     return pc.vstack(
>         pc.input(on_blur=State.add_query),
>         pc.heading(
>             pc.highlight(
>                 State.text, 
>                 query=State.query, 
>                 bg = "green",
>                 color = "red",
>                 px = "2",
>                 py = "1",
>                 rounded = "full",
> 
>             )
>         ),
>     )
> ```
> 
> https://github.com/pynecone-io/pynecone/blob/e9ca1fd03b7d1c3caade682bd9f1f2dca10f268a/pynecone/components/datadisplay/code.py#L52-L75

It's working right now.

**Comment by TaiJuWu** [comment]
> For this component should we take the stye props and pass them into the style dict similar to how it's done in code block. This would allow code like
> 
> ```python
> class State(pc.State):
>     """The app state."""
> 
>     text: str = "With the Highlight component, you can spotlight, emphasize and accentuate words."
>     query=['spotlight', 'emphasize', 'Accentuate']
>     styles={ 'px': '2', 'py': '1', 'rounded': 'full', 'bg': 'teal.100' }
>     
>     def add_query(self, query: str):
>         """Add a query to the list of queries."""
>         self.query.append(query)
>     
> def index():
>     """The main view."""
>     
>     return pc.vstack(
>         pc.input(on_blur=State.add_query),
>         pc.heading(
>             pc.highlight(
>                 State.text, 
>                 query=State.query, 
>                 bg = "green",
>                 color = "red",
>                 px = "2",
>                 py = "1",
>                 rounded = "full",
> 
>             )
>         ),
>     )
> ```
> 
> https://github.com/pynecone-io/pynecone/blob/e9ca1fd03b7d1c3caade682bd9f1f2dca10f268a/pynecone/components/datadisplay/code.py#L52-L75

It's working right now.

**Review by picklelo — APPROVED** [review]
nice!

**Pull request merged**
