### PR TITLE
Rename var module to vars

### LINKED ISSUE #982: Import ambiguity: var(module) / var(ComputedVar)
Pyright complains because it thinks I want to use the private module `var` when I decorate a method with `@pc.var`.

### PR DESCRIPTION
**Pull request by iron3oxide**
### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Closes #982

### CODE REVIEW

**Comment by iron3oxide** [comment]
Sorry that the old commits got in there as well, I've learned my lesson and will branch religiously now..

**Comment by iron3oxide** [comment]
Seems like VSCode couldn't differentiate between the two either and refactored the tests as well. On it

**Review by picklelo — APPROVED** [review]
nice

**Comment by picklelo** [comment]
I'll merge an update to `pcweb` which should pass the integration tests

**Pull request merged**
